



import { Component, OnInit } from '@angular/core';
import {
  ListCaptionConfig,
  ListHeader,
} from 'src/app/shared/models/List.model';

@Component({
  selector: 'app-table-v5',
  templateUrl: './table-v5.component.html',
  styleUrls: ['./table-v5.component.scss'],
})
export class TableV5Component {
  data = [
    {
      _id: 1,
      img: '../../assets/images/Zinzu Chan Lee.jpg',
      fullname: 'Zinzu Chan Lee',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: false,
      renge: 101,
      persentage: 10,
      age: 24,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 1,
          age: 24,
          category: ['adventuretime'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 601,
          persentage: 2,
          age: 23,
          category: ['beachlife'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 3,
          age: 28,
          category: ['catsofinstagram'],
          number: '$210.40',
        },
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 4,
          age: 24,
          category: ['datenightideas'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 5,
          age: 23,
          category: ['earlybird'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 6,
          age: 28,
          category: ['fashionista'],
          number: '$210.40',
        },
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 7,
          age: 24,
          category: ['gymmotivation'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 8,
          age: 23,
          category: ['healthyfood'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 9,
          age: 28,
          category: ['instatravel'],
          number: '$210.40',
        },
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 10,
          age: 24,
          category: ['journalling'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 11,
          age: 23,
          category: ['kindnessmatters'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 12,
          age: 28,
          category: ['lovelife'],
          number: '$210.40',
        },
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 13,
          age: 24,
          category: ['musiclover'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 14,
          age: 23,
          category: ['naturephotography'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 15,
          age: 28,
          category: ['onlinelearning'],
          number: '$210.40',
        },
      ],
      category: ['ahmed', 'positivityquotes'],
      number: '$5350.50',
    },
    {
      _id: 2,
      img: '../../assets/images/Jeet Saru.jpg',
      fullname: 'Jeet Saru',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: false,
      renge: 20,
      persentage: 20,
      age: 23,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 16,
          age: 24,
          category: ['quiettime'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 17,
          age: 23,
          category: ['runningcommunity'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 18,
          age: 28,
          category: ['selfcarematters'],
          number: '$210.40',
        },
      ],
      category: [, 'travelholic', '50kg'],
      number: '$5350.50',
    },
    {
      _id: 3,
      img: '../../assets/images/Sonal Gharti.jpg',
      fullname: 'Sonal Gharti',
      address: 'Tokyo',
      date: '14 Mar, 2023',
      stat: 'Shipped',
      valid: false,
      renge: 30,
      persentage: 30,
      age: 28,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 19,
          age: 24,
          category: ['uniquegifts'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 20,
          age: 23,
          category: ['vintagestyle'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 21,
          age: 28,
          category: ['workoutmotivation'],
          number: '$210.40',
        },
      ],
      category: ['yogaflow'],
      number: '$210.40',
    },
    {
      _id: 4,
      img: '../../assets/images/Alson GC.jpg',
      fullname: 'Alson GC',
      address: 'New Delhi',
      date: '25 May, 2023',
      stat: 'Delivered',
      valid: false,
      renge: 40,
      persentage: 40,
      age: 39,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 22,
          age: 24,
          category: ['zenmind'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 23,
          age: 23,
          category: ['arttherapy'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 24,
          age: 28,
          category: ['bookishlove'],
          number: '$210.40',
        },
      ],
      category: ['coffeeaddict'],
      number: '$149.70',
    },
    {
      _id: 5,
      img: '../../assets/images/Sarita Limbu.jpg',
      fullname: 'Sarita Limbu',
      address: 'Paris',
      date: '23 Apr, 2023',
      stat: 'Pending',
      valid: true,

      persentage: 50,
      age: 24,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 25,
          age: 24,
          category: ['doglovers'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 26,
          age: 23,
          category: ['brahim', 'exploretheworld'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 27,
          age: 28,
          category: ['familyfun'],
          number: '$210.40',
        },
      ],
      category: ['gratefulheart'],
      number: '$399.99',
    },
    {
      _id: 6,
      img: '../../assets/images/Alex Gonley.jpg',
      fullname: 'Alex Gonley',
      address: 'London',
      date: '23 Apr, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 28,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 29,
          age: 24,
          category: ['healthyhabits'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 30,
          age: 23,
          category: ['inspiration'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 31,
          age: 28,
          category: ['journaling'],
          number: '$210.40',
        },
      ],
      category: ['kindnessisfree'],
      number: '$399.99',
    },
    {
      _id: 7,
      img: '../../assets/images/Alson GC.jpg',
      fullname: 'Jeet Saru',
      address: 'New York',
      date: '20 May, 2023',
      stat: 'Delivered',
      valid: false,
      renge: 70,
      persentage: 70,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 32,
          age: 24,
          category: ['luxurylifestyle'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 33,
          age: 23,
          category: ['motivationmonday'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 34,
          age: 28,
          category: ['newbeginnings'],
          number: '$210.40',
        },
      ],
      category: ['organicliving'],
      number: '$399.99',
    },
    {
      _id: 8,
      img: '../../assets/images/Sarita Limbu.jpg',
      fullname: 'Aayat Ali Khan',
      address: 'Islamabad',
      date: '30 Feb, 2023',
      stat: 'Pending',
      valid: true,

      persentage: 35,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 36,
          age: 24,
          category: ['positivevibesonly'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 37,
          age: 23,
          category: ['quirkythings'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 38,
          age: 28,
          category: ['relaxationtime'],
          number: '$210.40',
        },
      ],
      category: ['selflove'],
      number: '$149.70',
    },
    {
      _id: 9,
      img: '../../assets/images/Alex Gonley.jpg',
      fullname: 'Alson GC',
      address: 'Dhaka',
      date: '22 Dec, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 39,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 40,
          age: 24,
          category: ['traveldiaries'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 41,
          age: 23,
          category: ['urbanexplorer'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 42,
          age: 28,
          category: ['weekendvibes'],
          number: '$210.40',
        },
      ],
      category: ['yogainspiration'],
      number: '$249.99',
    },
    {
      _id: 1,
      img: '../../assets/images/Zinzu Chan Lee.jpg',
      fullname: 'Zinzu Chan Lee',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 43,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 44,
          age: 24,
          category: ['zestforlife'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 45,
          age: 23,
          category: ['bookstagram'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 46,
          age: 28,
          category: ['cakedecorating'],
          number: '$210.40',
        },
      ],
      category: ['dailygratitude'],
      number: '$5350.50',
    },
    {
      _id: 2,
      img: '../../assets/images/Jeet Saru.jpg',
      fullname: 'Jeet Saru',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,
      persentage: 47,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 48,
          age: 24,
          category: ['50kg', 'entrepreneurmindset'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 49,
          age: 23,
          category: ['friendshipgoals'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 50,
          age: 28,
          category: ['goodvibes'],
          number: '$210.40',
        },
      ],
      category: ['hikingadventures'],
      number: '$5350.50',
    },
    {
      _id: 3,
      img: '../../assets/images/Sonal Gharti.jpg',
      fullname: 'Sonal Gharti',
      address: 'Tokyo',
      date: '14 Mar, 2023',
      stat: 'Shipped',
      valid: true,

      persentage: 51,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 52,
          age: 24,
          category: ['darck', 'inspirationalquotes'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 53,
          age: 23,
          category: ['justbreathe'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 54,
          age: 28,
          category: ['knittinglove'],
          number: '$210.40',
        },
      ],
      category: ['livewell'],
      number: '$210.40',
    },
    {
      _id: 1,
      img: '../../assets/images/Zinzu Chan Lee.jpg',
      fullname: 'Zinzu Chan Lee',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 55,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 56,
          age: 24,
          category: ['mindfulnesspractice'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 57,
          age: 23,
          category: ['newadventures', 'smale'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 58,
          age: 28,
          category: ['outdoorlife'],
          number: '$210.40',
        },
      ],
      category: ['positivityiskey'],
      number: '$5350.50',
    },
    {
      _id: 2,
      img: '../../assets/images/Jeet Saru.jpg',
      fullname: 'Jeet Saru',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 59,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 60,
          age: 24,
          category: ['quotesoftheday'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 61,
          age: 23,
          category: ['relaxingtime'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 62,
          age: 28,
          category: ['selfmotivation'],
          number: '$210.40',
        },
      ],
      category: ['travelgram'],
      number: '$5350.50',
    },
    {
      _id: 3,
      img: '../../assets/images/Sonal Gharti.jpg',
      fullname: 'Sonal Gharti',
      address: 'Tokyo',
      date: '14 Mar, 2023',
      stat: 'Shipped',
      valid: true,

      persentage: 63,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 64,
          age: 24,
          category: ['upcyclelove'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 65,
          age: 23,
          category: ['workhardplayhard'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 66,
          age: 28,
          category: ['yogalife'],
          number: '$210.40',
        },
      ],
      category: ['zerowaste'],
      number: '$210.40',
    },
    {
      _id: 4,
      img: '../../assets/images/Alson GC.jpg',
      fullname: 'Alson GC',
      address: 'New Delhi',
      date: '25 May, 2023',
      stat: 'Delivered',
      valid: true,

      persentage: 67,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 68,
          age: 24,
          category: ['beautifulplaces'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 69,
          age: 23,
          category: ['calligraphylove'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 70,
          age: 28,
          category: ['datenight'],
          number: '$210.40',
        },
      ],
      category: ['elevateyourself'],
      number: '$149.70',
    },
    {
      _id: 5,
      img: '../../assets/images/Sarita Limbu.jpg',
      fullname: 'Sarita Limbu',
      address: 'Paris',
      date: '23 Apr, 2023',
      stat: 'Pending',
      valid: true,

      persentage: 71,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 72,
          age: 24,
          category: ['friendshipquotes'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 73,
          age: 23,
          category: ['gratitudeattitude'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 74,
          age: 28,
          category: ['healthychoices'],
          number: '$210.40',
        },
      ],
      category: ['innerpeace'],
      number: '$399.99',
    },
    {
      _id: 6,
      img: '../../assets/images/Alex Gonley.jpg',
      fullname: 'Alex Gonley',
      address: 'London',
      date: '23 Apr, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 75,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 76,
          age: 24,
          category: ['justdoit'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 77,
          age: 23,
          category: ['kindnessiscontagious'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 78,
          age: 28,
          category: ['lovequotes'],
          number: '$210.40',
        },
      ],
      category: ['mindbodysoul'],
      number: '$399.99',
    },
    {
      _id: 7,
      img: '../../assets/images/Alson GC.jpg',
      fullname: 'Jeet Saru',
      address: 'New York',
      date: '20 May, 2023',
      stat: 'Delivered',
      valid: true,

      persentage: 79,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 80,
          age: 24,
          category: ['neverstopexploring'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 81,
          age: 23,
          category: ['organicbeauty'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 82,
          age: 28,
          category: ['positiveenergy'],
          number: '$210.40',
        },
      ],
      category: ['quotestoliveby'],
      number: '$399.99',
    },
    {
      _id: 8,
      img: '../../assets/images/Sarita Limbu.jpg',
      fullname: 'Aayat Ali Khan',
      address: 'Islamabad',
      date: '30 Feb, 2023',
      stat: 'Pending',
      valid: true,

      persentage: 83,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 84,
          age: 24,
          category: ['resilience'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 85,
          age: 23,
          category: ['simplicityliving'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 86,
          age: 28,
          category: ['takemeback'],
          number: '$210.40',
        },
      ],
      category: ['urbanjungle'],
      number: '$149.70',
    },
    {
      _id: 9,
      img: '../../assets/images/Alex Gonley.jpg',
      fullname: 'Alson GC',
      address: 'Dhaka',
      date: '22 Dec, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 87,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 88,
          age: 24,
          category: ['wanderlust'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 89,
          age: 23,
          category: ['yogaeverydamnday'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 90,
          age: 28,
          category: ['zinintheair'],
          number: '$210.40',
        },
      ],
      category: ['beautycommunity'],
      number: '$249.99',
    },
    {
      _id: 1,
      img: '../../assets/images/Zinzu Chan Lee.jpg',
      fullname: 'Zinzu Chan Lee',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 91,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 92,
          age: 24,
          category: ['collageart'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 93,
          age: 23,
          category: ['dailymotivation'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 94,
          age: 28,
          category: ['everydayadventures'],
          number: '$210.40',
        },
      ],
      category: ['foodiegram'],
      number: '$5350.50',
    },
    {
      _id: 2,
      img: '../../assets/images/Jeet Saru.jpg',
      fullname: 'Jeet Saru',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 95,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 96,
          age: 24,
          category: ['goodfriends'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 97,
          age: 23,
          category: ['happinessproject'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 98,
          age: 28,
          category: ['inspirationdaily'],
          number: '$210.40',
        },
      ],
      category: ['justbeauty'],
      number: '$5350.50',
    },
    {
      _id: 3,
      img: '../../assets/images/Sonal Gharti.jpg',
      fullname: 'Sonal Gharti',
      address: 'Tokyo',
      date: '14 Mar, 2023',
      stat: 'Shipped',
      valid: true,

      persentage: 99,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 100,
          age: 24,
          category: ['knittinginspiration'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 101,
          age: 23,
          category: ['livethelittlethings'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 102,
          age: 28,
          category: ['mindsetiseverything'],
          number: '$210.40',
        },
      ],
      category: ['naturelover'],
      number: '$210.40',
    },
    {
      _id: 1,
      img: '../../assets/images/Zinzu Chan Lee.jpg',
      fullname: 'Zinzu Chan Lee',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 103,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 104,
          age: 24,
          category: ['oceanview'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 105,
          age: 23,
          category: ['personaldevelopment'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 106,
          age: 28,
          category: ['quotesaboutlife'],
          number: '$210.40',
        },
      ],
      category: ['runninglife'],
      number: '$5350.50',
    },
    {
      _id: 2,
      img: '../../assets/images/Jeet Saru.jpg',
      fullname: 'Jeet Saru',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 107,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 108,
          age: 24,
          category: ['simplepleasures'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 109,
          age: 23,
          category: ['thriftstorefinds'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 110,
          age: 28,
          category: ['unwindtime'],
          number: '$210.40',
        },
      ],
      category: ['wellnessjourney'],
      number: '$5350.50',
    },
    {
      _id: 3,
      img: '../../assets/images/Sonal Gharti.jpg',
      fullname: 'Sonal Gharti',
      address: 'Tokyo',
      date: '14 Mar, 2023',
      stat: 'Shipped',
      valid: true,

      persentage: 111,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 112,
          age: 24,
          category: ['yogalifestyle'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 113,
          age: 23,
          category: ['zerowasteliving'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 114,
          age: 28,
          category: ['bakinglove'],
          number: '$210.40',
        },
      ],
      category: ['candlelover'],
      number: '$210.40',
    },
    {
      _id: 4,
      img: '../../assets/images/Alson GC.jpg',
      fullname: 'Alson GC',
      address: 'New Delhi',
      date: '25 May, 2023',
      stat: 'Delivered',
      valid: true,

      persentage: 115,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 116,
          age: 24,
          category: ['determinedmindset'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 117,
          age: 23,
          category: ['encouragement'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 118,
          age: 28,
          category: ['freedomthinkers'],
          number: '$210.40',
        },
      ],
      category: ['goodnightpost'],
      number: '$149.70',
    },
    {
      _id: 5,
      img: '../../assets/images/Sarita Limbu.jpg',
      fullname: 'Sarita Limbu',
      address: 'Paris',
      date: '23 Apr, 2023',
      stat: 'Pending',
      valid: true,

      persentage: 119,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 120,
          age: 24,
          category: ['happymoments'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 121,
          age: 23,
          category: ['intentionalliving'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 122,
          age: 28,
          category: ['joyfulheart'],
          number: '$210.40',
        },
      ],
      category: ['kindnessalways'],
      number: '$399.99',
    },
    {
      _id: 6,
      img: '../../assets/images/Alex Gonley.jpg',
      fullname: 'Alex Gonley',
      address: 'London',
      date: '23 Apr, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 123,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 124,
          age: 24,
          category: ['lovemylife'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 125,
          age: 23,
          category: ['motivationalquotes'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 126,
          age: 28,
          category: ['newdaynewstart'],
          number: '$210.40',
        },
      ],
      category: ['organizingtips'],
      number: '$399.99',
    },
    {
      _id: 7,
      img: '../../assets/images/Alson GC.jpg',
      fullname: 'Jeet Saru',
      address: 'New York',
      date: '20 May, 2023',
      stat: 'Delivered',
      valid: true,

      persentage: 127,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 128,
          age: 24,
          category: ['positiveaffirmations'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 129,
          age: 23,
          category: ['quoteoftheday'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 130,
          age: 28,
          category: ['resilientmindset'],
          number: '$210.40',
        },
      ],
      category: ['simplifyyourlife'],
      number: '$399.99',
    },
    {
      _id: 8,
      img: '../../assets/images/Sarita Limbu.jpg',
      fullname: 'Aayat Ali Khan',
      address: 'Islamabad',
      date: '30 Feb, 2023',
      stat: 'Pending',
      valid: true,

      persentage: 131,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 132,
          age: 24,
          category: ['takingtime'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 133,
          age: 23,
          category: ['upliftingquotes'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 134,
          age: 28,
          category: ['weekendfun'],
          number: '$210.40',
        },
      ],
      category: ['yogapose'],
      number: '$149.70',
    },
    {
      _id: 9,
      img: '../../assets/images/Alex Gonley.jpg',
      fullname: 'Alson GC',
      address: 'Dhaka',
      date: '22 Dec, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 135,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 136,
          age: 24,
          category: ['zinnow'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 137,
          age: 23,
          category: ['beautylover'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 138,
          age: 28,
          category: ['colorfulart'],
          number: '$210.40',
        },
      ],
      category: ['dailyaffirmation'],
      number: '$249.99',
    },
    {
      _id: 1,
      img: '../../assets/images/Zinzu Chan Lee.jpg',
      fullname: 'Zinzu Chan Lee',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 139,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 140,
          age: 24,
          category: ['everythingispossible'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 141,
          age: 23,
          category: ['forgiveyourself'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 142,
          age: 28,
          category: ['gratefulness'],
          number: '$210.40',
        },
      ],
      category: ['happythoughts'],
      number: '$5350.50',
    },
    {
      _id: 2,
      img: '../../assets/images/Jeet Saru.jpg',
      fullname: 'Jeet Saru',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 143,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 144,
          age: 24,
          category: ['inspiredaily'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 145,
          age: 23,
          category: ['justbeyou'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 146,
          age: 28,
          category: ['knittingtherapy'],
          number: '$210.40',
        },
      ],
      category: ['loveyourselffirst'],
      number: '$5350.50',
    },
    {
      _id: 3,
      img: '../../assets/images/Sonal Gharti.jpg',
      fullname: 'Sonal Gharti',
      address: 'Tokyo',
      date: '14 Mar, 2023',
      stat: 'Shipped',
      valid: true,

      persentage: 147,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 148,
          age: 24,
          category: ['mindsetofgreatness'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 149,
          age: 23,
          category: ['newexperiences'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 150,
          age: 28,
          category: ['outdooradventures'],
          number: '$210.40',
        },
      ],
      category: ['positivemindset'],
      number: '$210.40',
    },
    {
      _id: 1,
      img: '../../assets/images/Zinzu Chan Lee.jpg',
      fullname: 'Zinzu Chan Lee',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 151,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 152,
          age: 24,
          category: ['quarantineandchill'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 153,
          age: 23,
          category: ['restoration'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 154,
          age: 28,
          category: ['selfdevelopment'],
          number: '$210.40',
        },
      ],
      category: ['thankfulgratefulblessed'],
      number: '$5350.50',
    },
    {
      _id: 2,
      img: '../../assets/images/Jeet Saru.jpg',
      fullname: 'Jeet Saru',
      address: 'Kathmandu',
      date: '27 Aug, 2023',
      stat: 'Cancelled',
      valid: true,

      persentage: 155,
      renge: 12,
      age: 27,
      templet: [
        {
          _id: 1,
          img: '../../assets/images/Zinzu Chan Lee.jpg',
          fullname: 'Zinzu Chan Lee',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 156,
          age: 24,
          category: ['unconditionallove'],
          number: '$5350.50',
        },
        {
          _id: 2,
          img: '../../assets/images/Jeet Saru.jpg',
          fullname: 'Jeet Saru',
          address: 'Kathmandu',
          date: '27 Aug, 2023',
          stat: 'Cancelled',
          valid: false,
          renge: 60,
          persentage: 157,
          age: 23,
          category: ['wellnesswarrior'],
          number: '$5350.50',
        },
        {
          _id: 3,
          img: '../../assets/images/Sonal Gharti.jpg',
          fullname: 'Sonal Gharti',
          address: 'Tokyo',
          date: '14 Mar, 2023',
          stat: 'Shipped',
          valid: false,
          renge: 60,
          persentage: 158,
          age: 28,
          category: ['yogapractice'],
          number: '$210.40',
        },
      ],
      category: ['zerowastetips'],
      number: '$5350.50',
    },
  ];

  cols: ListHeader[] = [
    {
      field: 'img',
      header: 'img',
      sort: true,
      filter: false,
      filterType: 'img',
      filterData: [],
    },
    {
      field: 'fullname',
      header: 'fullname',
      sort: true,
      filter: true,
      filterType: 'text',
      filterData: [],
    },
    {
      field: 'persentage',
      header: 'persant',
      sort: true,
      filter: true,
      filterType: 'percentage',
      filterData: [],
    },
    {
      field: 'renge',
      header: 'range',
      sort: true,
      filter: true,
      filterType: 'range',
      filterData: [],
    },
    {
      field: 'age',
      header: 'age',
      sort: true,
      filter: true,
      filterType: 'numeric',
      filterData: [],
    },
    {
      field: 'category',
      header: 'category',
      sort: true,
      filter: true,
      filterType: 'chips',
      filterData: [],
    },
    {
      field: 'valid',
      header: 'valid',
      sort: true,
      filter: true,
      filterType: 'boolean',
      filterData: [],
      colorize: { red: false, green: true },
    },
    {
      field: 'date',
      header: 'date',
      sort: true,
      filter: false,
      filterType: 'date',
      filterData: [],
    },
    {
      field: 'templet',
      header: 'list',
      sort: true,
      templatePath: ['category', 'img', 'age'],
      filter: false,
      filterType: 'template',
      // optionLabel: 'fullname',
      filterData: [],
    },
    {
      field: 'address',
      header: 'address',
      sort: true,
      filter: false,
      filterType: 'address',

      filterData: [],
    },
    {
      field: 'number',
      header: 'price',
      sort: true,
      filter: false,
      filterType: 'price',
      filterData: [],
    },
  ];

  // dummyDate: any[] =
  // [
  //   {
  //     _id: 1,
  //     first_name: 'Bryant',
  //     last_name: 'Gomes',
  //     email: 'bgomes0@reddit.com',
  //     gender: 'Male',
  //     stat: 'Infiniti',
  //     car_model: 2003,
  //     ctiy: 'Jerada',
  //     country: 'Morocco',
  //     country_code: 'MA',
  //     company: 'Safetec of America, Inc.',
  //   },
  //   {
  //     _id: 2,
  //     first_name: 'Julita',
  //     last_name: 'Antoney',
  //     email: 'jantoney1@symantec.com',
  //     gender: 'Female',
  //     car: 'Jaguar',
  //     car_model: 2009,
  //     ctiy: 'Orléans',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Uriel Pharmacy Inc.',
  //   },
  //   {
  //     _id: 3,
  //     first_name: 'Nap',
  //     last_name: 'Hackforth',
  //     email: 'nhackforth2@fotki.com',
  //     gender: 'Male',
  //     car: 'Chevrolet',
  //     car_model: 2004,
  //     ctiy: 'Taounate',
  //     country: 'Morocco',
  //     country_code: 'MA',
  //     company: 'CHAIN DRUG MARKETING ASSOCIATION INC',
  //   },
  //   {
  //     _id: 4,
  //     first_name: 'Viole',
  //     last_name: 'Briiginshaw',
  //     email: 'vbriiginshaw3@t.co',
  //     gender: 'Female',
  //     car: 'Land Rover',
  //     car_model: 2001,
  //     ctiy: 'Paris La Défense',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'RUGBY LABORATORIES, INC.',
  //   },
  //   {
  //     _id: 5,
  //     first_name: 'Chere',
  //     last_name: 'Laden',
  //     email: 'claden4@smh.com.au',
  //     gender: 'Female',
  //     car: 'Infiniti',
  //     car_model: 2006,
  //     ctiy: 'Saint-Julien-en-Genevois',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Taro Pharmaceuticals U.S.A., Inc.',
  //   },
  //   {
  //     _id: 6,
  //     first_name: 'Nigel',
  //     last_name: 'Odger',
  //     email: 'nodger5@meetup.com',
  //     gender: 'Male',
  //     car: 'Infiniti',
  //     car_model: 2003,
  //     ctiy: 'Amboise',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'State of Florida DOH Central Pharmacy',
  //   },
  //   {
  //     _id: 7,
  //     first_name: 'Hakim',
  //     last_name: 'Beades',
  //     email: 'hbeades6@ask.com',
  //     gender: 'Male',
  //     car: 'BMW',
  //     car_model: 2006,
  //     ctiy: 'Levallois-Perret',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Walgreen Company',
  //   },
  //   {
  //     _id: 8,
  //     first_name: 'Hayley',
  //     last_name: 'Marcu',
  //     email: 'hmarcu7@privacy.gov.au',
  //     gender: 'Female',
  //     car: 'Ford',
  //     car_model: 2006,
  //     ctiy: 'Rabat',
  //     country: 'Morocco',
  //     country_code: 'MA',
  //     company: 'REMEDYREPACK INC.',
  //   },
  //   {
  //     _id: 9,
  //     first_name: 'Alexio',
  //     last_name: 'Barge',
  //     email: 'abarge8@hc360.com',
  //     gender: 'Male',
  //     car: 'Buick',
  //     car_model: 1986,
  //     ctiy: 'Roanne',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Cardinal Health',
  //   },
  //   {
  //     _id: 10,
  //     first_name: 'Lucias',
  //     last_name: 'Coch',
  //     email: 'lcoch9@yellowpages.com',
  //     gender: 'Male',
  //     car: 'Dodge',
  //     car_model: 2002,
  //     ctiy: 'Bobigny',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Moore Medical LLC',
  //   },
  //   {
  //     _id: 11,
  //     first_name: 'Orren',
  //     last_name: 'Bims',
  //     email: 'obimsa@pinterest.com',
  //     gender: 'Polygender',
  //     car: 'Saturn',
  //     car_model: 2001,
  //     ctiy: 'Pontarlier',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Accord Healthcare Inc.',
  //   },
  //   {
  //     _id: 12,
  //     first_name: 'Harlan',
  //     last_name: 'Casella',
  //     email: 'hcasellab@technorati.com',
  //     gender: 'Male',
  //     car: 'Buick',
  //     car_model: 1988,
  //     ctiy: 'Saint-Quentin-en-Yvelines',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'ANIP Acquisition Company',
  //   },
  //   {
  //     _id: 13,
  //     first_name: 'Beverie',
  //     last_name: 'Oakley',
  //     email: 'boakleyc@friendfeed.com',
  //     gender: 'Female',
  //     car: 'Mercury',
  //     car_model: 1997,
  //     ctiy: 'Cergy-Pontoise',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'BioActive Nutritional, Inc.',
  //   },
  //   {
  //     _id: 14,
  //     first_name: 'Paquito',
  //     last_name: 'Silliman',
  //     email: 'psillimand@nyu.edu',
  //     gender: 'Male',
  //     car: 'Chevrolet',
  //     car_model: 1963,
  //     ctiy: 'Aviles',
  //     country: 'Spain',
  //     country_code: 'ES',
  //     company: 'Oral-B Laboratories',
  //   },
  //   {
  //     _id: 15,
  //     first_name: 'Reggy',
  //     last_name: 'Pane',
  //     email: 'rpanee@soundcloud.com',
  //     gender: 'Male',
  //     car: 'Chevrolet',
  //     car_model: 2006,
  //     ctiy: 'Bressuire',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Target Corporation',
  //   },
  //   {
  //     _id: 16,
  //     first_name: 'Madge',
  //     last_name: 'Caramuscia',
  //     email: 'mcaramusciaf@unesco.org',
  //     gender: 'Female',
  //     car: 'Pontiac',
  //     car_model: 1986,
  //     ctiy: 'Reims',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Elizabeth Arden, Inc',
  //   },
  //   {
  //     _id: 17,
  //     first_name: 'Scarface',
  //     last_name: 'Salling',
  //     email: 'ssallingg@barnesandnoble.com',
  //     gender: 'Male',
  //     car: 'GMC',
  //     car_model: 1994,
  //     ctiy: 'Longjumeau',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Home Sweet Homeopathics',
  //   },
  //   {
  //     _id: 18,
  //     first_name: 'Valaria',
  //     last_name: 'Sapir',
  //     email: 'vsapirh@hibu.com',
  //     gender: 'Female',
  //     car: 'Honda',
  //     car_model: 1995,
  //     ctiy: 'Annecy',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Janssen Pharmaceuticals, Inc.',
  //   },
  //   {
  //     _id: 19,
  //     first_name: 'Laure',
  //     last_name: 'Di Biaggi',
  //     email: 'ldibiaggii@cdbaby.com',
  //     gender: 'Female',
  //     car: 'GMC',
  //     car_model: 2011,
  //     ctiy: 'Donostia-San Sebastian',
  //     country: 'Spain',
  //     country_code: 'ES',
  //     company: 'ViiV Healthcare Company',
  //   },
  //   {
  //     _id: 20,
  //     first_name: 'Nappie',
  //     last_name: 'Maywood',
  //     email: 'nmaywoodj@statcounter.com',
  //     gender: 'Male',
  //     car: 'Toyota',
  //     car_model: 2001,
  //     ctiy: 'Paris 10',
  //     country: 'France',
  //     country_code: 'FR',
  //     company: 'Mylan Institutional Inc.',
  //   },
  // ];
  captionConfigb: ListCaptionConfig = {
    tibleTitale: 'tible titale b',
    globalFilter: false,
    csv: true,
    pdf: true,
    xls: true,
    selection: true,
    displayedColumns: true,
    headerFilterType: 'text-header',
    headerFilterfield: 'fullname',
    clearTable: true,
    refreshData: true,
    addButton: true,
    imgPopUp: true,
    selectionType: 'single',
    summary: {
      enabled: true,
      message: ' In Total there are {{data.length}} elements .',
    },
    expanded: {},
    actions: {
      clone: true,
      delete: true,
      edit: true,
      detail: true,
    },
  };
  captionConfig: ListCaptionConfig = {
    globalFilter: false,
    csv: true,
    pdf: true,
    xls: true,
    selection: true,
    displayedColumns: true,
    clearTable: true,
    refreshData: true,
    addButton: true,
    imgPopUp: true,
    headerFilterType: 'text-header',
    headerFilterfield: 'fullname',
    selectionType: 'multiple',
    summary: {
      enabled: true,
      message: ' In Total there are {{data.length}} elements .',
    },
    expanded: {
      dataField: 'templet',
      headers: this.cols,
      captionConfig: this.captionConfigb,
    },
    actions: {
      clone: true,
      delete: true,
      edit: true,
      detail: true,
    },
  };
  darkMode: any;
  onEditClick(i: any) {}
  onDetailClick(i: any) {}
  onCloneClick(i: any) {}
  onAddClick(i: any) {}
  onDelete(i: any) {}
  ngOnInit(): void {
    this.darkMode = JSON.parse(sessionStorage.getItem('darkMode') || 'false');
    console.log(this.darkMode);
  }
 
  setTimeOutId: any = -1;
  
 
  
  onRefreshClick($event: boolean) {
    let a = this.data;
    this.data = [];
   clearTimeout(this.setTimeOutId);
   this.setTimeOutId = setTimeout(() => {
     this.data = a;
   }, 2000);
  }
}
